builds:
- id: main
  dir: .  # default
  main: ./main.go
  env:
  - CGO_ENABLED=0
  flags:
  - -tags
  - netgo
  ldflags:
  - -s -w
  - -extldflags "-static"
  - -X main.version={{.Env.RELEASE}}
  - -X main.commit={{.Env.GIT_COMMIT}}